# Generated by Django 4.0.5 on 2022-06-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
