# Generated by Django 3.2.14 on 2022-10-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0003_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videoclases.organizer'),
        ),
    ]
