# Generated by Django 3.2.14 on 2022-11-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0004_homework_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='school',
        ),
        migrations.AddField(
            model_name='organizer',
            name='school',
            field=models.ManyToManyField(blank=True, to='videoclases.School'),
        ),
    ]
