# Generated by Django 3.2.14 on 2022-11-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclases', '0005_auto_20221102_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='school',
            new_name='schools',
        ),
    ]
