# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videoclases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('homework', models.ManyToManyField(to='videoclases.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='QualityItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('criteria', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.CASCADE,
                                               to='videoclases.Criterion')),
                ('teacher', models.ForeignKey(blank=True, null=True,
                                              on_delete=django.db.models.deletion.CASCADE,
                                              to='videoclases.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='qualityitem',
            name='score_check',
            field=models.ManyToManyField(to='quality_control.QualityScore'),
        ),
        migrations.AddField(
            model_name='qualityitem',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE,
                                    to='videoclases.Teacher'),
        ),
        migrations.AddField(
            model_name='qualityitem',
            name='videoclase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualityItemList',
                                    to='videoclases.VideoClase'),
        ),
        migrations.AddField(
            model_name='qualitycontrol',
            name='list_items',
            field=models.ManyToManyField(to='quality_control.QualityItem'),
        ),
    ]
